-   id: sql-formatter
    name: sql-formatter
    description: Reformat SQL files with sql-formatter
    entry: sql-formatter --fix
    language: node
    types: [sql]
    additional_dependencies: ["sql-formatter@12.1.0"]
