-   id: sql-formatter
    name: Format SQL files
    description: 'Reformat SQL files with sql-formatter'
    entry: pre-commit-sql-formatter
    language: node
    types: [sql]
    additional_dependencies: ["sql-formatter@12.0.6"]
    args: [--language=snowflake]
