-   id: sql-formatter
    name: sql-formatter
    description: 'Reformat SQL files with sql-formatter'
    entry: node ./script.mjs
    language: node
    'types': [sql]
    args: []
    require_serial: false
    additional_dependencies: ["sql-formatter@12.0.6"]
